name: HCL OneTest Server

on:
    workflow_dispatch:
        inputs:
            server_url:
                description: 'Server URL'
                required: true
            offline_token:
                description: 'Offline Token'
                required: true
            team_space:
                description: 'Team Space Name'
                required: true
            project:
                description: 'Project'
                required: true
            branch:
                description: 'Branch'
                required: true
            assetId:
                description: 'AssetID'
                required: true
            environment:
                description: 'API Test Environment'
                required: false
            datasets:
                description: 'Datasets'
                required: false
            exportReport:
                description: 'Export Junit Report'
                required: false
            multipleValues:
                description: 'Multiple Values'
                required: false

jobs:

    OTS-Action:
        runs-on: self-hosted
        name: HCL OneTest Server
        steps:
         - name: Execute Test
           uses: SonaHJ/OTSAction@HCLOneTestServer_03
           with:
            serverUrl: '${{ github.event.inputs.server_url }}'
            offlineToken: '${{ github.event.inputs.offline_token }}'
            teamspace: '${{ github.event.inputs.team_space }}'
            project: '${{ github.event.inputs.project }}'
            branch: '${{ github.event.inputs.branch }}'
            assetId: '${{ github.event.inputs.assetId }}'
            environment: '${{ github.event.inputs.environment }}'
            datasets: '${{ github.event.inputs.datasets }}'
            exportReport: '${{ github.event.inputs.exportReport }}'
            multipleValues: '${{ github.event.inputs.multipleValues }}'
